### ISSUE TITLE
cmake build for demos

### ISSUE THREAD

**Issue by baselqyqony** [gerazo/pipert#10]
I get the following error when I try to build and run demos :
I use the command cmake --build for building source files there , is there any additional setting I should do before build?
"REAL_BBTEST_SOURCES

/usr/bin/ld: cannot find -lpipert
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/simple.dir/build.make:84: simple] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/simple.dir/all] Error 2
make: *** [Makefile:84: all] Error 2 "

**Comment by ip1996** [comment]
Currently demo is just a playground, and it is not updated with the project. 
And it tries to find the pipert lib in the ../build folder, but that folder is only created when you build the project with the build.sh script file.
So what I can suggest:
```
./build.sh
cd demo
mkdir build
cd build
cmake ..
make
```
Or just modify the *link_directories* property in the demo CMakeLists.txt to *../build_release*, if you want to go with the devbuild.sh.

**Comment by baselqyqony** [comment]
ok thank you

**Comment by gerazo** [comment]
I think @martinb214 is busy converting this demo into one of the tests. I will live on there.

**Comment by gerazo** [comment]
@martinb214  on https://github.com/gerazo/pipert/pull/13 could integrate this into our tests. What do you think @ip1996 ? Can we remove the demo folder?

**Comment by ip1996** [comment]
Yes, I think we can.

**Comment by martinb214** [comment]
Okay, then I convert them into tests and drop the demo folder.

**Comment by gerazo** [comment]
@martinb214 Thanks. If the PR went in, we can also close this.

**Comment by gerazo** [comment]
@martinb214 I see that tests went in, but the demo folder is still there. I think, we could remove it in order to solve this issue.

**Comment by martinb214** [comment]
@gerazo I think existing test cases are not like demos, so my current goal is to create tests which have hints about the usage of the Scheduler. As soon as these test cases are implemented I will remove the demos folder completely. I'm going to create a PR for this soon.
