### ISSUE TITLE
Log Analyzer and Performance Monitor

### ISSUE THREAD

**Issue by gerazo** [gerazo/pipert#11]
We need an app which will be able to
 - Receive logs created by https://github.com/gerazo/pipert/issues/6
 - Show logs in real-time and visualize them
 - Make certain analysis
   - Weakest points, bottlenecks
   - Overall system performance and latency
   - Dataflow mapping, pipeline visualizatun of current system

**Comment by Hossam-Abdin** [comment]
@gerazo it should be closed now,, right?
