### ISSUE TITLE
Use anonymous namespace in every test

### ISSUE THREAD

**Issue by gerazo** [gerazo/pipert#18]
Check that every of our tests use the anonymous namespace for local definitions!

**Comment by gerazo** [comment]
@BenBlaise If you are working on ActiveSpinLock, please also put everything into anonymous namespace. I will do it with the rest of the test files.

**Comment by BenBlaise** [comment]
Just pushed a new commit to unit_testing. All definitions in AdaptiveSpinLockTest.cpp should be in an anonymous namespace now.

**Comment by gerazo** [comment]
Cool, I have done it to the other tests. Here is the PR: https://github.com/gerazo/pipert/pull/22 Can you quickly review?

**Comment by gerazo** [comment]
All tests now got this, so we are fine.
