### ISSUE TITLE
Separate heap-in-fixed-size-vector container functionality into separate class

### ISSUE THREAD

**Issue by gerazo** [gerazo/pipert#31]
We are using a special type of heap in `ChannelImpl::queued_packets_`, `SchedulerImpl::state_queue_` and in `SchedulerImpl::state2channel_queues_` as the value side of the key.value pairs. These heaps have the following important features:
 - They are `std::vector`s which do not change during runtime. They are constant in size during operation.
 - They are heaps inside and use `std::push_heap()` and `std::pop_heap()` algorithms to keep up the heap condition.
 - They accept custom ordering (see the code) between the elements (but this should be a strict ordering).
 - They have a special operation: they can update an element in the heap by removing and re-adding it. (See the code!)

It would be good to have such a class separately in order to keep the two mentioned implementation classes minimal.
This is a rather complex refactoring task.

**Comment by BenBlaise** [comment]
I've started working on the issue, and I might emerge with a solution soon.

**Comment by BenBlaise** [comment]
A potential solution has been pushed to `steady_heap`, and the issue is expected to be closed upon merging PR #33.
